### ISSUE TITLE
使用rt-thread studio导入mdk工程文件，需要重新定义gpio。

### ISSUE THREAD

**Issue by jack17951** [RT-Thread/IoT_Board#16]
使用rt-thread studio导入mdk工程文件，需要重新定义gpio。才能使示例跑起来，发现是没有driver下的定义，是我哪里没有搞对么。

**Comment by armink** [comment]
@SummerLife 看下这个问题吧

**Comment by SummerGift** [comment]
@jack17951 你这里说需要重新定义 gpio 是什么意思呢，能贴图或者给出更详细的描述吗？
