### ISSUE TITLE
IoT_Board的源代码是否可以开源

### ISSUE THREAD

**Issue by wangAeA** [RT-Thread/IoT_Board#7]
在RTT在越来越流行，越来越多的人认识它，了解它并且开始使用它的基础下，IoT_Board代码的开源可以让RTT的生态更加成熟，也能让大家能够更深刻的认识它，支持它。也能让RTT发展的更加快。更加深入人心。因此，我想询问下这部分的代码是否有开源计划？

**Comment by hellozimo** [comment]
这个仓库已经是开源了的代码啊

**Comment by wangAeA** [comment]
> 
> 
> 这个仓库已经是开源了的代码啊

其中是有lib库的，比如BootLoader相关的代码。

**Comment by balanceTWK** [comment]
开源、免费（商用也免费）啊啊啊，咋会有这种问题。。。

**Comment by hellozimo** [comment]
@wangAeA bootloader 部分 RTT 有提供 STM32 通用 bootloader 生成工具，不支持开发者自定义，目的是降低开发难度，也为了保证 bootloader 进行 OTA 的安全可靠。

其他库文件，也是一样的目的。

如果有定制化的需求，欢迎商务合作。
